import { Injectable } from '@angular/core';
import { Habitation } from '../../models/habitation';
import { HttpClient } from '@angular/common/http';
import { map } from 'rxjs/operators';

@Injectable({
  providedIn: 'root'
})
export class ClientService {

  private url = 'https://hotel-86b0a-default-rtdb.firebaseio.com';
  
  habitations: Habitation[] = Data;

  constructor( private _http: HttpClient ) { }

  getTypeHabitation(){

    return this._http.get(`${ this.url }/tipo_habitacion.json`)
                  .pipe(
                      map( this.crearArreglo )
                  );
  }

  getServices(){

    return this._http.get(`${ this.url }/servicios.json`)
                  .pipe(
                    map( this.crearArreglo )
                  );                  
  }


  newMovie( movie: any ){

    return this._http.post(`${ this.url }/movies.json`, movie);

  }


  getHabitations(){
    return this.habitations;
  }


  private crearArreglo( datasObj: object ){

    const datas: any[] = [];
    const imgs: any[] = [];

    if ( datasObj === null ) { return []; }

    Object.keys( datasObj ).forEach( key => {

      const data: any = datasObj[key];
      data.id = key;

      if( data.imgs) {
        var img: any[] = [];
        Object.keys( data.imgs ).forEach( key => {
  
          img.push(data.imgs[key]);
  
        });
        data.imgs = img;
      }

      datas.push( data );     
     
    });

    return datas;
  }

  
}


export const Data: any[] = [
  { id: '123',  images: ['https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ab5/59b19cab56693889036245.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ef1/59b19cef19c9e021287242.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/5b0/857/ec3/5b0857ec31a6a493350480.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/2ff/378/59b2ff378714c511913412.jpg'],  type: 'duplex',        price: 36.738,  status: 'limpia',          num: '1', description: 'Nuestro hotel está diseñado tanto para altos ejecutivos y empresarios como para quienes deseen alojarse y disfrutar de una estancia relajante y de placer, estamos orgullosos de presentar nuestra Executive Suite con una dimensión de 80 m², la cual está decorada con un estilo moderno y colores cálidos. En ella podrá disfrutar de la comodidad y la elegancia de su dormitorio así como una gran sala de estar, lo suficientemente grande como para relajarse, trabajar, o incluso organizar una reunión. La Executive Suite dispone de comodidades para su confort, incluido el acceso Wi-Fi a Internet, minibar, caja fuerte electrónica, televisión LCD de alta definición y un amplio baño en el cual podrá disfrutar de una relajante ducha y bañera con hidromasajes, así como una exclusiva selección de amenidades.' },
  { id: '456',  images: ['https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ab5/59b19cab56693889036245.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ef1/59b19cef19c9e021287242.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/5b0/857/ec3/5b0857ec31a6a493350480.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/2ff/378/59b2ff378714c511913412.jpg'], type: 'duplex',        price: 23.789,  status: 'ocupada',         num: '2' , description: 'Nuestro hotel está diseñado tanto para altos ejecutivos y empresarios como para quienes deseen alojarse y disfrutar de una estancia relajante y de placer, estamos orgullosos de presentar nuestra Executive Suite con una dimensión de 80 m², la cual está decorada con un estilo moderno y colores cálidos. En ella podrá disfrutar de la comodidad y la elegancia de su dormitorio así como una gran sala de estar, lo suficientemente grande como para relajarse, trabajar, o incluso organizar una reunión. La Executive Suite dispone de comodidades para su confort, incluido el acceso Wi-Fi a Internet, minibar, caja fuerte electrónica, televisión LCD de alta definición y un amplio baño en el cual podrá disfrutar de una relajante ducha y bañera con hidromasajes, así como una exclusiva selección de amenidades.' },
  { id: '789',  images: ['https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ab5/59b19cab56693889036245.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ef1/59b19cef19c9e021287242.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/5b0/857/ec3/5b0857ec31a6a493350480.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/2ff/378/59b2ff378714c511913412.jpg'], type: 'duplex',        price: 36.738,  status: 'mantenimiento',   num: '3' , description: 'Nuestro hotel está diseñado tanto para altos ejecutivos y empresarios como para quienes deseen alojarse y disfrutar de una estancia relajante y de placer, estamos orgullosos de presentar nuestra Executive Suite con una dimensión de 80 m², la cual está decorada con un estilo moderno y colores cálidos. En ella podrá disfrutar de la comodidad y la elegancia de su dormitorio así como una gran sala de estar, lo suficientemente grande como para relajarse, trabajar, o incluso organizar una reunión. La Executive Suite dispone de comodidades para su confort, incluido el acceso Wi-Fi a Internet, minibar, caja fuerte electrónica, televisión LCD de alta definición y un amplio baño en el cual podrá disfrutar de una relajante ducha y bañera con hidromasajes, así como una exclusiva selección de amenidades.' },
  { id: '101',  images: ['https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ab5/59b19cab56693889036245.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ef1/59b19cef19c9e021287242.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/5b0/857/ec3/5b0857ec31a6a493350480.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/2ff/378/59b2ff378714c511913412.jpg'], type: 'duplex',        price: 56.142,  status: 'limpia',          num: '4' , description: 'Nuestro hotel está diseñado tanto para altos ejecutivos y empresarios como para quienes deseen alojarse y disfrutar de una estancia relajante y de placer, estamos orgullosos de presentar nuestra Executive Suite con una dimensión de 80 m², la cual está decorada con un estilo moderno y colores cálidos. En ella podrá disfrutar de la comodidad y la elegancia de su dormitorio así como una gran sala de estar, lo suficientemente grande como para relajarse, trabajar, o incluso organizar una reunión. La Executive Suite dispone de comodidades para su confort, incluido el acceso Wi-Fi a Internet, minibar, caja fuerte electrónica, televisión LCD de alta definición y un amplio baño en el cual podrá disfrutar de una relajante ducha y bañera con hidromasajes, así como una exclusiva selección de amenidades.' },
  { id: '102',  images: ['https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ab5/59b19cab56693889036245.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ef1/59b19cef19c9e021287242.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/5b0/857/ec3/5b0857ec31a6a493350480.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/2ff/378/59b2ff378714c511913412.jpg'], type: 'duplex',        price: 38.735,  status: 'mantenimiento',   num: '5' , description: 'Nuestro hotel está diseñado tanto para altos ejecutivos y empresarios como para quienes deseen alojarse y disfrutar de una estancia relajante y de placer, estamos orgullosos de presentar nuestra Executive Suite con una dimensión de 80 m², la cual está decorada con un estilo moderno y colores cálidos. En ella podrá disfrutar de la comodidad y la elegancia de su dormitorio así como una gran sala de estar, lo suficientemente grande como para relajarse, trabajar, o incluso organizar una reunión. La Executive Suite dispone de comodidades para su confort, incluido el acceso Wi-Fi a Internet, minibar, caja fuerte electrónica, televisión LCD de alta definición y un amplio baño en el cual podrá disfrutar de una relajante ducha y bañera con hidromasajes, así como una exclusiva selección de amenidades.' },
  { id: '103',  images: ['https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ab5/59b19cab56693889036245.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ef1/59b19cef19c9e021287242.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/5b0/857/ec3/5b0857ec31a6a493350480.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/2ff/378/59b2ff378714c511913412.jpg'], type: 'duplex',        price: 36.738,  status: 'desocupada',      num: '6' , description: 'Nuestro hotel está diseñado tanto para altos ejecutivos y empresarios como para quienes deseen alojarse y disfrutar de una estancia relajante y de placer, estamos orgullosos de presentar nuestra Executive Suite con una dimensión de 80 m², la cual está decorada con un estilo moderno y colores cálidos. En ella podrá disfrutar de la comodidad y la elegancia de su dormitorio así como una gran sala de estar, lo suficientemente grande como para relajarse, trabajar, o incluso organizar una reunión. La Executive Suite dispone de comodidades para su confort, incluido el acceso Wi-Fi a Internet, minibar, caja fuerte electrónica, televisión LCD de alta definición y un amplio baño en el cual podrá disfrutar de una relajante ducha y bañera con hidromasajes, así como una exclusiva selección de amenidades.' },
  { id: '104',  images: ['https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ab5/59b19cab56693889036245.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ef1/59b19cef19c9e021287242.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/5b0/857/ec3/5b0857ec31a6a493350480.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/2ff/378/59b2ff378714c511913412.jpg'], type: 'matrimonial',   price: 36.738,  status: 'limpia',          num: '7' , description: 'Nuestro hotel está diseñado tanto para altos ejecutivos y empresarios como para quienes deseen alojarse y disfrutar de una estancia relajante y de placer, estamos orgullosos de presentar nuestra Executive Suite con una dimensión de 80 m², la cual está decorada con un estilo moderno y colores cálidos. En ella podrá disfrutar de la comodidad y la elegancia de su dormitorio así como una gran sala de estar, lo suficientemente grande como para relajarse, trabajar, o incluso organizar una reunión. La Executive Suite dispone de comodidades para su confort, incluido el acceso Wi-Fi a Internet, minibar, caja fuerte electrónica, televisión LCD de alta definición y un amplio baño en el cual podrá disfrutar de una relajante ducha y bañera con hidromasajes, así como una exclusiva selección de amenidades.' },
  { id: '105',  images: ['https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ab5/59b19cab56693889036245.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ef1/59b19cef19c9e021287242.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/5b0/857/ec3/5b0857ec31a6a493350480.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/2ff/378/59b2ff378714c511913412.jpg'], type: 'matrimonial',   price: 56.142,  status: 'mantenimiento',   num: '8' , description: 'Nuestro hotel está diseñado tanto para altos ejecutivos y empresarios como para quienes deseen alojarse y disfrutar de una estancia relajante y de placer, estamos orgullosos de presentar nuestra Executive Suite con una dimensión de 80 m², la cual está decorada con un estilo moderno y colores cálidos. En ella podrá disfrutar de la comodidad y la elegancia de su dormitorio así como una gran sala de estar, lo suficientemente grande como para relajarse, trabajar, o incluso organizar una reunión. La Executive Suite dispone de comodidades para su confort, incluido el acceso Wi-Fi a Internet, minibar, caja fuerte electrónica, televisión LCD de alta definición y un amplio baño en el cual podrá disfrutar de una relajante ducha y bañera con hidromasajes, así como una exclusiva selección de amenidades.' },
  { id: '106',  images: ['https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ab5/59b19cab56693889036245.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ef1/59b19cef19c9e021287242.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/5b0/857/ec3/5b0857ec31a6a493350480.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/2ff/378/59b2ff378714c511913412.jpg'], type: 'matrimonial',   price: 36.738,  status: 'limpia',          num: '9' , description: 'Nuestro hotel está diseñado tanto para altos ejecutivos y empresarios como para quienes deseen alojarse y disfrutar de una estancia relajante y de placer, estamos orgullosos de presentar nuestra Executive Suite con una dimensión de 80 m², la cual está decorada con un estilo moderno y colores cálidos. En ella podrá disfrutar de la comodidad y la elegancia de su dormitorio así como una gran sala de estar, lo suficientemente grande como para relajarse, trabajar, o incluso organizar una reunión. La Executive Suite dispone de comodidades para su confort, incluido el acceso Wi-Fi a Internet, minibar, caja fuerte electrónica, televisión LCD de alta definición y un amplio baño en el cual podrá disfrutar de una relajante ducha y bañera con hidromasajes, así como una exclusiva selección de amenidades.' },
  { id: '107',  images: ['https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ab5/59b19cab56693889036245.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ef1/59b19cef19c9e021287242.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/5b0/857/ec3/5b0857ec31a6a493350480.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/2ff/378/59b2ff378714c511913412.jpg'], type: 'matrimonial',   price: 36.738,  status: 'ocupada',         num: '10', description: 'Nuestro hotel está diseñado tanto para altos ejecutivos y empresarios como para quienes deseen alojarse y disfrutar de una estancia relajante y de placer, estamos orgullosos de presentar nuestra Executive Suite con una dimensión de 80 m², la cual está decorada con un estilo moderno y colores cálidos. En ella podrá disfrutar de la comodidad y la elegancia de su dormitorio así como una gran sala de estar, lo suficientemente grande como para relajarse, trabajar, o incluso organizar una reunión. La Executive Suite dispone de comodidades para su confort, incluido el acceso Wi-Fi a Internet, minibar, caja fuerte electrónica, televisión LCD de alta definición y un amplio baño en el cual podrá disfrutar de una relajante ducha y bañera con hidromasajes, así como una exclusiva selección de amenidades.' },
  { id: '108',  images: ['https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ab5/59b19cab56693889036245.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ef1/59b19cef19c9e021287242.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/5b0/857/ec3/5b0857ec31a6a493350480.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/2ff/378/59b2ff378714c511913412.jpg'], type: 'matrimonial',   price: 23.789,  status: 'limpia',          num: '11', description: 'Nuestro hotel está diseñado tanto para altos ejecutivos y empresarios como para quienes deseen alojarse y disfrutar de una estancia relajante y de placer, estamos orgullosos de presentar nuestra Executive Suite con una dimensión de 80 m², la cual está decorada con un estilo moderno y colores cálidos. En ella podrá disfrutar de la comodidad y la elegancia de su dormitorio así como una gran sala de estar, lo suficientemente grande como para relajarse, trabajar, o incluso organizar una reunión. La Executive Suite dispone de comodidades para su confort, incluido el acceso Wi-Fi a Internet, minibar, caja fuerte electrónica, televisión LCD de alta definición y un amplio baño en el cual podrá disfrutar de una relajante ducha y bañera con hidromasajes, así como una exclusiva selección de amenidades.' },
  { id: '109',  images: ['https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ab5/59b19cab56693889036245.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ef1/59b19cef19c9e021287242.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/5b0/857/ec3/5b0857ec31a6a493350480.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/2ff/378/59b2ff378714c511913412.jpg'], type: 'matrimonial',   price: 36.738,  status: 'mantenimiento',   num: '12', description: 'Nuestro hotel está diseñado tanto para altos ejecutivos y empresarios como para quienes deseen alojarse y disfrutar de una estancia relajante y de placer, estamos orgullosos de presentar nuestra Executive Suite con una dimensión de 80 m², la cual está decorada con un estilo moderno y colores cálidos. En ella podrá disfrutar de la comodidad y la elegancia de su dormitorio así como una gran sala de estar, lo suficientemente grande como para relajarse, trabajar, o incluso organizar una reunión. La Executive Suite dispone de comodidades para su confort, incluido el acceso Wi-Fi a Internet, minibar, caja fuerte electrónica, televisión LCD de alta definición y un amplio baño en el cual podrá disfrutar de una relajante ducha y bañera con hidromasajes, así como una exclusiva selección de amenidades.' },
  { id: '110',  images: ['https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ab5/59b19cab56693889036245.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ef1/59b19cef19c9e021287242.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/5b0/857/ec3/5b0857ec31a6a493350480.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/2ff/378/59b2ff378714c511913412.jpg'], type: 'matrimonial',   price: 38.735,  status: 'desocupada',      num: '13', description: 'Nuestro hotel está diseñado tanto para altos ejecutivos y empresarios como para quienes deseen alojarse y disfrutar de una estancia relajante y de placer, estamos orgullosos de presentar nuestra Executive Suite con una dimensión de 80 m², la cual está decorada con un estilo moderno y colores cálidos. En ella podrá disfrutar de la comodidad y la elegancia de su dormitorio así como una gran sala de estar, lo suficientemente grande como para relajarse, trabajar, o incluso organizar una reunión. La Executive Suite dispone de comodidades para su confort, incluido el acceso Wi-Fi a Internet, minibar, caja fuerte electrónica, televisión LCD de alta definición y un amplio baño en el cual podrá disfrutar de una relajante ducha y bañera con hidromasajes, así como una exclusiva selección de amenidades.' },
  { id: '111',  images: ['https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ab5/59b19cab56693889036245.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/19c/ef1/59b19cef19c9e021287242.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/5b0/857/ec3/5b0857ec31a6a493350480.jpg', 'https://www.hoteleshesperia.com.ve/storage/app/uploads/public/59b/2ff/378/59b2ff378714c511913412.jpg'], type: 'matrimonial',   price: 78.615,  status: 'ocupada',         num: '14', description: 'Nuestro hotel está diseñado tanto para altos ejecutivos y empresarios como para quienes deseen alojarse y disfrutar de una estancia relajante y de placer, estamos orgullosos de presentar nuestra Executive Suite con una dimensión de 80 m², la cual está decorada con un estilo moderno y colores cálidos. En ella podrá disfrutar de la comodidad y la elegancia de su dormitorio así como una gran sala de estar, lo suficientemente grande como para relajarse, trabajar, o incluso organizar una reunión. La Executive Suite dispone de comodidades para su confort, incluido el acceso Wi-Fi a Internet, minibar, caja fuerte electrónica, televisión LCD de alta definición y un amplio baño en el cual podrá disfrutar de una relajante ducha y bañera con hidromasajes, así como una exclusiva selección de amenidades.' }

]